version: "3.7"
services:
  web:
    build:
      context: ./api
    environment:
      FLASK_DEBUG: "on"
      FLASK_APP: ./app.py
      GITHUB_API_TOKEN: ${GITHUB_API_TOKEN}
    restart: always
    ports:
     - "5001:5001"
    volumes: ['./api:/api']
